name: Update SCB data monthly

on:
  schedule:
    - cron: "0 5 12 * *"  # 05:00 UTC on the 12th (~06:00/07:00 CET/CEST)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run updater
        run: |
          python scripts/update_data.py

      - name: Commit and push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: monthly SCB update"
            git push
          else
            echo "No changes to commit."
          fi
